export const Players = [
  {
    id: 1,
    firstName: "Damián",
    middleName: "Emiliano",
    lastName: "Martínez",
    dateOfBirth: "1992-09-02T00:00:00.000Z",
    squadNumber: 23,
    position: "Goalkeeper",
    abbrPosition: "GK",
    team: "Aston Villa FC",
    league: "Premier League",
    starting11: 1,
  },
  {
    id: 2,
    firstName: "Nahuel",
    middleName: null,
    lastName: "Molina",
    dateOfBirth: "1998-04-06T00:00:00.000Z",
    squadNumber: 26,
    position: "Right-Back",
    abbrPosition: "RB",
    team: "Atlético Madrid",
    league: "La Liga",
    starting11: 1,
  },
  {
    id: 3,
    firstName: "Cristian",
    middleName: "Gabriel",
    lastName: "Romero",
    dateOfBirth: "1998-04-27T00:00:00.000Z",
    squadNumber: 13,
    position: "Centre-Back",
    abbrPosition: "CB",
    team: "Tottenham Hotspur",
    league: "Premier League",
    starting11: 1,
  },
  {
    id: 4,
    firstName: "Nicolás",
    middleName: "Hernán Gonzalo",
    lastName: "Otamendi",
    dateOfBirth: "1988-02-12T00:00:00.000Z",
    squadNumber: 19,
    position: "Centre-Back",
    abbrPosition: "CB",
    team: "SL Benfica",
    league: "Liga Portugal",
    starting11: 1,
  },
  {
    id: 5,
    firstName: "Nicolás",
    middleName: "Alejandro",
    lastName: "Tagliafico",
    dateOfBirth: "1992-08-31T00:00:00.000Z",
    squadNumber: 3,
    position: "Left-Back",
    abbrPosition: "LB",
    team: "Olympique Lyon",
    league: "Ligue 1",
    starting11: 1,
  },
  {
    id: 6,
    firstName: "Ángel",
    middleName: "Fabián",
    lastName: "Di María",
    dateOfBirth: "1988-02-14T00:00:00.000Z",
    squadNumber: 11,
    position: "Right Winger",
    abbrPosition: "LW",
    team: "SL Benfica",
    league: "Liga Portugal",
    starting11: 1,
  },
  {
    id: 7,
    firstName: "Rodrigo",
    middleName: "Javier",
    lastName: "de Paul",
    dateOfBirth: "1994-05-24T00:00:00.000Z",
    squadNumber: 7,
    position: "Central Midfield",
    abbrPosition: "CM",
    team: "Atlético Madrid",
    league: "La Liga",
    starting11: 1,
  },
  {
    id: 8,
    firstName: "Enzo",
    middleName: "Jeremías",
    lastName: "Fernández",
    dateOfBirth: "2001-01-17T00:00:00.000Z",
    squadNumber: 24,
    position: "Central Midfield",
    abbrPosition: "CM",
    team: "Chelsea FC",
    league: "Premier League",
    starting11: 1,
  },
  {
    id: 9,
    firstName: "Alexis",
    middleName: null,
    lastName: "Mac Allister",
    dateOfBirth: "1998-12-24T00:00:00.000Z",
    squadNumber: 20,
    position: "Central Midfield",
    abbrPosition: "CM",
    team: "Liverpool FC",
    league: "Premier League",
    starting11: 1,
  },
  {
    id: 10,
    firstName: "Lionel",
    middleName: "Andrés",
    lastName: "Messi",
    dateOfBirth: "1987-06-24T00:00:00.000Z",
    squadNumber: 10,
    position: "Right Winger",
    abbrPosition: "RW",
    team: "Inter Miami CF",
    league: "Major League Soccer",
    starting11: 1,
  },
  {
    id: 11,
    firstName: "Julián",
    middleName: null,
    lastName: "Álvarez",
    dateOfBirth: "2000-01-31T00:00:00.000Z",
    squadNumber: 9,
    position: "Centre-Forward",
    abbrPosition: "CF",
    team: "Manchester City",
    league: "Premier League",
    starting11: 1,
  },
  {
    id: 12,
    firstName: "Franco",
    middleName: "Daniel",
    lastName: "Armani",
    dateOfBirth: "1986-10-16T00:00:00.000Z",
    squadNumber: 1,
    position: "Goalkeeper",
    abbrPosition: "GK",
    team: "River Plate",
    league: "Copa de la Liga",
    starting11: 0,
  },
  {
    id: 13,
    firstName: "Gerónimo",
    middleName: null,
    lastName: "Rulli",
    dateOfBirth: "1992-05-20T00:00:00.000Z",
    squadNumber: 12,
    position: "Goalkeeper",
    abbrPosition: "GK",
    team: "Ajax Amsterdam",
    league: "Eredivisie",
    starting11: 0,
  },
  {
    id: 14,
    firstName: "Juan",
    middleName: "Marcos",
    lastName: "Foyth",
    dateOfBirth: "1998-01-12T00:00:00.000Z",
    squadNumber: 2,
    position: "Right-Back",
    abbrPosition: "RB",
    team: "Villareal",
    league: "La Liga",
    starting11: 0,
  },
  {
    id: 15,
    firstName: "Gonzalo",
    middleName: "Ariel",
    lastName: "Montiel",
    dateOfBirth: "1997-01-01T00:00:00.000Z",
    squadNumber: 4,
    position: "Right-Back",
    abbrPosition: "RB",
    team: "Nottingham Forrest",
    league: "Premier League",
    starting11: 0,
  },
  {
    id: 16,
    firstName: "Germán",
    middleName: "Alejo",
    lastName: "Pezzella",
    dateOfBirth: "1991-06-27T00:00:00.000Z",
    squadNumber: 6,
    position: "Centre-Back",
    abbrPosition: "CB",
    team: "Real Betis Balompié",
    league: "La Liga",
    starting11: 0,
  },
  {
    id: 17,
    firstName: "Marcos",
    middleName: "Javier",
    lastName: "Acuña",
    dateOfBirth: "1991-10-28T00:00:00.000Z",
    squadNumber: 8,
    position: "Left-Back",
    abbrPosition: "LB",
    team: "Sevilla FC",
    league: "La Liga",
    starting11: 0,
  },
  {
    id: 18,
    firstName: "Lisandro",
    middleName: null,
    lastName: "Martínez",
    dateOfBirth: "1998-01-18T00:00:00.000Z",
    squadNumber: 25,
    position: "Centre-Back",
    abbrPosition: "CB",
    team: "Manchester United",
    league: "Premier League",
    starting11: 0,
  },
  {
    id: 19,
    firstName: "Leandro",
    middleName: "Daniel",
    lastName: "Paredes",
    dateOfBirth: "1994-06-29T00:00:00.000Z",
    squadNumber: 5,
    position: "Defensive Midfield",
    abbrPosition: "DM",
    team: "AS Roma",
    league: "Serie A",
    starting11: 0,
  },
  {
    id: 20,
    firstName: "Exequiel",
    middleName: "Alejandro",
    lastName: "Palacios",
    dateOfBirth: "1998-10-05T00:00:00.000Z",
    squadNumber: 14,
    position: "Central Midfield",
    abbrPosition: "CM",
    team: "Bayer 04 Leverkusen",
    league: "Bundesliga",
    starting11: 0,
  },
  {
    id: 21,
    firstName: "Alejandro",
    middleName: "Darío",
    lastName: "Gómez",
    dateOfBirth: "1988-02-15T00:00:00.000Z",
    squadNumber: 17,
    position: "Left Winger",
    abbrPosition: "LW",
    team: "AC Monza",
    league: "Serie A",
    starting11: 0,
  },
  {
    id: 22,
    firstName: "Guido",
    middleName: null,
    lastName: "Rodríguez",
    dateOfBirth: "1994-04-12T00:00:00.000Z",
    squadNumber: 18,
    position: "Defensive Midfield",
    abbrPosition: "DM",
    team: "Real Betis Balompié",
    league: "La Liga",
    starting11: 0,
  },
  {
    id: 23,
    firstName: "Ángel",
    middleName: "Martín",
    lastName: "Correa",
    dateOfBirth: "1995-03-09T00:00:00.000Z",
    squadNumber: 15,
    position: "Right Winger",
    abbrPosition: "RW",
    team: "Atlético Madrid",
    league: "La Liga",
    starting11: 0,
  },
  {
    id: 24,
    firstName: "Thiago",
    middleName: "Ezequiel",
    lastName: "Almada",
    dateOfBirth: "2001-04-26T00:00:00.000Z",
    squadNumber: 16,
    position: "Attacking Midfield",
    abbrPosition: "AM",
    team: "Atlanta United FC",
    league: "Major League Soccer",
    starting11: 0,
  },
  {
    id: 25,
    firstName: "Paulo",
    middleName: "Exequiel",
    lastName: "Dybala",
    dateOfBirth: "1993-11-15T00:00:00.000Z",
    squadNumber: 21,
    position: "Second Striker",
    abbrPosition: "SS",
    team: "AS Roma",
    league: "Serie A",
    starting11: 0,
  },
  {
    id: 26,
    firstName: "Lautaro",
    middleName: "Javier",
    lastName: "Martínez",
    dateOfBirth: "1997-08-22T00:00:00.000Z",
    squadNumber: 22,
    position: "Centre-Forward",
    abbrPosition: "CF",
    team: "Inter Milan",
    league: "Serie A",
    starting11: 0,
  },
];
