export const Songs = [
  {
    album: "Highway 61 Revisited",
    artist: "Bob Dylan",
    rank: 1,
    title: "Like a Rolling Stone",
    year: 1965,
  },
  {
    album: "Out of Our Heads",
    artist: "The Rolling Stones",
    rank: 2,
    title: "(I Can't Get No) Satisfaction",
    year: 1965,
  },
  {
    album: "Imagine",
    artist: "John Lennon",
    rank: 3,
    title: "Imagine",
    year: 1971,
  },
  {
    album: "What's Going On",
    artist: "Marvin Gaye",
    rank: 4,
    title: "What's Going On",
    year: 1971,
  },
  {
    album: "I Never Loved a Man the Way I Love You",
    artist: "Aretha Franklin",
    rank: 5,
    title: "Respect",
    year: 1967,
  },
  {
    album: "Smiley Smile/Wild Honey",
    artist: "The Beach Boys",
    rank: 6,
    title: "Good Vibrations",
    year: 1966,
  },
  {
    album: "The Anthology",
    artist: "Chuck Berry",
    rank: 7,
    title: "Johnny B. Goode",
    year: 1958,
  },
  {
    album: "Hey Jude",
    artist: "The Beatles",
    rank: 8,
    title: "Hey Jude",
    year: 1968,
  },
  {
    album: "Nevermind",
    artist: "Nirvana",
    rank: 9,
    title: "Smells Like Teen Spirit",
    year: 1991,
  },
  {
    album: "What'd I Say",
    artist: "Ray Charles",
    rank: 10,
    title: "What'd I Say",
    year: 1959,
  },
  {
    album: "My Generation",
    artist: "The Who",
    rank: 11,
    title: "My Generation",
    year: 1965,
  },
  {
    album: "Portrait of a Legend 1951-1964",
    artist: "Sam Cooke",
    rank: 12,
    title: "A Change Is Gonna Come",
    year: 1964,
  },
  {
    album: "Help!",
    artist: "The Beatles",
    rank: 13,
    title: "Yesterday",
    year: 1965,
  },
  {
    album: "The Freewheelin' Bob Dylan",
    artist: "Bob Dylan",
    rank: 14,
    title: "Blowin' in the Wind",
    year: 1963,
  },
  {
    album: "London Calling",
    artist: "The Clash",
    rank: 15,
    title: "London Calling",
    year: 1980,
  },
  {
    album: "Meet the Beatles!",
    artist: "The Beatles",
    rank: 16,
    title: "I Want to Hold Your Hand",
    year: 1963,
  },
  {
    album: "Are You Experienced?",
    artist: "The Jimi Hendrix Experience",
    rank: 17,
    title: "Purple Haze",
    year: 1967,
  },
  {
    album: "The Anthology",
    artist: "Chuck Berry",
    rank: 18,
    title: "Maybellene",
    year: 1955,
  },
  {
    album: " Elvis 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 19,
    title: "Hound Dog",
    year: 1956,
  },
  {
    album: "Let It Be",
    artist: "The Beatles",
    rank: 20,
    title: "Let It Be",
    year: 1970,
  },
  {
    album: "Born to Run",
    artist: "Bruce Springsteen",
    rank: 21,
    title: "Born to Run",
    year: 1975,
  },
  {
    album: "The Best of the Ronettes",
    artist: "The Ronettes",
    rank: 22,
    title: "Be My Baby",
    year: 1963,
  },
  {
    album: "Rubber Soul",
    artist: "The Beatles",
    rank: 23,
    title: "In My Life",
    year: 1965,
  },
  {
    album: "The Very Best of the Impressions",
    artist: "The Impressions",
    rank: 24,
    title: "People Get Ready",
    year: 1965,
  },
  {
    album: "Pet Sounds",
    artist: "The Beach Boys",
    rank: 25,
    title: "God Only Knows",
    year: 1966,
  },
  {
    album: "The Dock of the Bay",
    artist: "Otis Redding",
    rank: 26,
    title: "(Sittin' On) The Dock of the Bay",
    year: 1968,
  },
  {
    album: "Layla And Other Assorted Love Songs",
    artist: "Derek and the Dominos",
    rank: 27,
    title: "Layla",
    year: 1970,
  },
  {
    album: "Sgt. Pepper's Lonely Hearts Club Band",
    artist: "The Beatles",
    rank: 28,
    title: "A Day in the Life",
    year: 1967,
  },
  {
    album: "Help!",
    artist: "The Beatles",
    rank: 29,
    title: "Help!",
    year: 1965,
  },
  {
    album: "The Complete Original Sun Singles",
    artist: "Johnny Cash",
    rank: 30,
    title: "I Walk the Line",
    year: 1956,
  },
  {
    album: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    rank: 31,
    title: "Stairway to Heaven",
    year: 1971,
  },
  {
    album: "Beggars Banquet",
    artist: "The Rolling Stones",
    rank: 32,
    title: "Sympathy for the Devil",
    year: 1968,
  },
  {
    album: "Proud Mary: The Best of Ike and Tina Turner",
    artist: "Ike & Tina Turner",
    rank: 33,
    title: "River Deep - Mountain High",
    year: 1966,
  },
  {
    album: "Anthology 1962-1974",
    artist: "The Righteous Brothers",
    rank: 34,
    title: "You've Lost That Lovin' Feelin'",
    year: 1964,
  },
  {
    album: "The Doors",
    artist: "The Doors",
    rank: 35,
    title: "Light My Fire",
    year: 1967,
  },
  {
    album: "Achtung Baby",
    artist: "U2",
    rank: 36,
    title: "One",
    year: 1991,
  },
  {
    album: "Natty Dread",
    artist: "Bob Marley & The Wailers",
    rank: 37,
    title: "No Woman, No Cry",
    year: 1975,
  },
  {
    album: "Let It Bleed",
    artist: "The Rolling Stones",
    rank: 38,
    title: "Gimme Shelter",
    year: 1969,
  },
  {
    album: "Greatest Hits",
    artist: "Buddy Holly & The Crickets",
    rank: 39,
    title: "That'll Be the Day",
    year: 1957,
  },
  {
    album: "The Ultimate Collection",
    artist: "Martha and the Vandellas",
    rank: 40,
    title: "Dancing in the Street",
    year: 1964,
  },
  {
    album: "Music From Big Pink",
    artist: "The Band",
    rank: 41,
    title: "The Weight",
    year: 1968,
  },
  {
    album: "Something Else By The Kinks",
    artist: "The Kinks",
    rank: 42,
    title: "Waterloo Sunset",
    year: 1968,
  },
  {
    album: "The Georgia Peach",
    artist: "Little Richard",
    rank: 43,
    title: "Tutti-Frutti",
    year: 1956,
  },
  {
    album: "Ultimate Hits Collection",
    artist: "Ray Charles",
    rank: 44,
    title: "Georgia On My Mind",
    year: 1960,
  },
  {
    album: "Elvis 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 45,
    title: "Heartbreak Hotel",
    year: 1956,
  },
  {
    album: "Heroes",
    artist: "David Bowie",
    rank: 46,
    title: "Heroes",
    year: 1977,
  },
  {
    album: "Electric Ladyland",
    artist: "The Jimi Hendrix Experience",
    rank: 47,
    title: "All Along the Watchtower",
    year: 1968,
  },
  {
    album: "Bridge Over Troubled Water",
    artist: "Simon & Garfunkel",
    rank: 48,
    title: "Bridge Over Troubled Water",
    year: 1970,
  },
  {
    album: "Hotel California",
    artist: "Eagles",
    rank: 49,
    title: "Hotel California",
    year: 1976,
  },
  {
    album: "Going to a Go-Go",
    artist: "Smokey Robinson and the Miracles",
    rank: 50,
    title: "The Tracks Of My Tears",
    year: 1965,
  },
  {
    album: "The Best of Sugar Hill Records",
    artist: "Grandmaster Flash and the Furious Five",
    rank: 51,
    title: "The Message",
    year: 1980,
  },
  {
    album: "Purple Rain",
    artist: "Prince and The Revolution",
    rank: 52,
    title: "When Doves Cry",
    year: 1984,
  },
  {
    album: "It Tears Me Up: The Best of Percy Sledge",
    artist: "Percy Sledge",
    rank: 53,
    title: "When A Man Loves A Woman",
    year: 1966,
  },
  {
    album: "The Best of the Kingsmen",
    artist: "The Kingsmen",
    rank: 54,
    title: "Louie Louie",
    year: 1963,
  },
  {
    album: "The Georgia Peach",
    artist: "Little Richard",
    rank: 55,
    title: "Long Tall Sally",
    year: 1956,
  },
  {
    album: "Never Mind the Bollocks, Here's the Sex Pistols",
    artist: "Sex Pistols",
    rank: 56,
    title: "Anarchy in the U.K.",
    year: 1976,
  },
  {
    album: "Greatest Hits",
    artist: "Procol Harum",
    rank: 57,
    title: "A Whiter Shade of Pale",
    year: 1967,
  },
  {
    album: "Thriller",
    artist: "Michael Jackson",
    rank: 58,
    title: "Billie Jean",
    year: 1983,
  },
  {
    album: "The Times They Are A-Changin'",
    artist: "Bob Dylan",
    rank: 59,
    title: "The Times They Are a-Changin'",
    year: 1964,
  },
  {
    album: "Let's Stay Together",
    artist: "Al Green",
    rank: 60,
    title: "Let's Stay Together",
    year: 1971,
  },
  {
    album: "Original Sun Greatest Hits",
    artist: "Jerry Lee Lewis",
    rank: 61,
    title: "Whole Lotta Shakin' Going On",
    year: 1957,
  },
  {
    album: "His Best: The Chess 50th Anniversary Collection",
    artist: "Bo Diddley",
    rank: 62,
    title: "Bo Diddley",
    year: 1955,
  },
  {
    album: "Buffalo Springfield",
    artist: "Buffalo Springfield",
    rank: 63,
    title: "For What It's Worth",
    year: 1967,
  },
  {
    album: "The Beatles 1",
    artist: "The Beatles",
    rank: 64,
    title: "She Loves You",
    year: 1963,
  },
  {
    album: "Disraeli Gears",
    artist: "Cream",
    rank: 65,
    title: "Sunshine of Your Love",
    year: 1968,
  },
  {
    album: "Uprising",
    artist: "Bob Marley & The Wailers",
    rank: 66,
    title: "Redemption Song",
    year: 1980,
  },
  {
    album: "Elvis 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 67,
    title: "Jailhouse Rock",
    year: 1957,
  },
  {
    album: "Blood on the Tracks",
    artist: "Bob Dylan",
    rank: 68,
    title: "Tangled Up in Blue",
    year: 1975,
  },
  {
    album: "For the Lonely: 18 Greatest Hits",
    artist: "Roy Orbison",
    rank: 69,
    title: "Crying",
    year: 1961,
  },
  {
    album: "The Dionne Warwick Collection: Her All-Time Greatest Hits",
    artist: "Dionne Warwick",
    rank: 70,
    title: "Walk On By",
    year: 1964,
  },
  {
    album: "50th Anniversary Collection",
    artist: "James Brown",
    rank: 71,
    title: "Papa's Got a Brand New Bag",
    year: 1966,
  },
  {
    album: "Sounds of Summer: The Very Best of the Beach Boys",
    artist: "The Beach Boys",
    rank: 72,
    title: "California Girls",
    year: 1965,
  },
  {
    album: "Talking Book",
    artist: "Stevie Wonder",
    rank: 73,
    title: "Superstition",
    year: 1973,
  },
  {
    album: "Somethin' Else",
    artist: "Eddie Cochran",
    rank: 74,
    title: "Summertime Blues",
    year: 1958,
  },
  {
    album: "Led Zeppelin II",
    artist: "Led Zeppelin",
    rank: 75,
    title: "Whole Lotta Love",
    year: 1969,
  },
  {
    album: "Magical Mystery Tour",
    artist: "The Beatles",
    rank: 76,
    title: "Strawberry Fields Forever",
    year: 1967,
  },
  {
    album: "Sunrise",
    artist: "Elvis Presley",
    rank: 77,
    title: "Mystery Train",
    year: 1955,
  },
  {
    album: "James Brown 50th Anniversary Collection",
    artist: "James Brown",
    rank: 78,
    title: "I Got You (I Feel Good)",
    year: 1966,
  },
  {
    album: "Mr. Tambourine Man",
    artist: "The Byrds",
    rank: 79,
    title: "Mr. Tambourine Man",
    year: 1965,
  },
  {
    album: "Kinks",
    artist: "The Kinks",
    rank: 80,
    title: "You Really Got Me",
    year: 1964,
  },
  {
    album: "Every Motown Hit",
    artist: "Marvin Gaye",
    rank: 81,
    title: "I Heard It Through the Grapevine",
    year: 1968,
  },
  {
    album: "The Fats Domino Jukebox",
    artist: "Fats Domino",
    rank: 82,
    title: "Blueberry Hill",
    year: 1956,
  },
  {
    album: "Rubber Soul",
    artist: "The Beatles",
    rank: 83,
    title: "Norwegian Wood (This Bird Has Flown)",
    year: 1965,
  },
  {
    album: "Synchronicity",
    artist: "The Police",
    rank: 84,
    title: "Every Breath You Take",
    year: 1983,
  },
  {
    album: "Patsy Cline's Greatest Hits",
    artist: "Patsy Cline",
    rank: 85,
    title: "Crazy",
    year: 1961,
  },
  {
    album: "Born to Run",
    artist: "Bruce Springsteen",
    rank: 86,
    title: "Thunder Road",
    year: 1975,
  },
  {
    album: "The Man in Black: His Greatest Hits",
    artist: "Johnny Cash",
    rank: 87,
    title: "Ring of Fire",
    year: 1963,
  },
  {
    album: "The Temptations Sing Smokey",
    artist: "The Temptations",
    rank: 88,
    title: "My Girl",
    year: 1965,
  },
  {
    album: "If You Can Believe Your Eyes And Ears",
    artist: "The Mamas & The Papas",
    rank: 89,
    title: "California Dreamin'",
    year: 1965,
  },
  {
    album: "The Five Satins: Their Greatest Hits",
    artist: "The Five Satins",
    rank: 90,
    title: "In The Still Of The Nite",
    year: 1956,
  },
  {
    album: "Elvis 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 91,
    title: "Suspicious Minds",
    year: 1969,
  },
  {
    album: "Ramones",
    artist: "Ramones",
    rank: 92,
    title: "Blitzkrieg Bop",
    year: 1976,
  },
  {
    album: "The Joshua Tree",
    artist: "U2",
    rank: 93,
    title: "I Still Haven't Found What I'm Looking For",
    year: 1987,
  },
  {
    album: "The Georgia Peach",
    artist: "Little Richard",
    rank: 94,
    title: "Good Golly",
    year: 1958,
  },
  {
    album: "Original Sun Greatest Hits",
    artist: "Carl Perkins",
    rank: 95,
    title: "Blue Suede Shoes",
    year: 1956,
  },
  {
    album: "Original Sun Greatest Hits",
    artist: "Jerry Lee Lewis",
    rank: 96,
    title: "Great Balls of Fire",
    year: 1957,
  },
  {
    album: "The Anthology",
    artist: "Chuck Berry",
    rank: 97,
    title: "Roll Over Beethoven",
    year: 1956,
  },
  {
    album: "I'm Still in Love With You",
    artist: "Al Green",
    rank: 98,
    title: "Love And Happiness",
    year: 1972,
  },
  {
    album: "Willy And The Poor Boys",
    artist: "Creedence Clearwater Revival",
    rank: 99,
    title: "Fortunate Son",
    year: 1970,
  },
  {
    album: "St. Elsewhere",
    artist: "Gnarls Barkley",
    rank: 100,
    title: "Crazy",
    year: 2006,
  },
  {
    album: "Let It Bleed",
    artist: "The Rolling Stones",
    rank: 101,
    title: "You Can't Always Get What You Want",
    year: 1969,
  },
  {
    album: "Electric Ladyland",
    artist: "The Jimi Hendrix Experience",
    rank: 102,
    title: "Voodoo Child (Slight Return)",
    year: 1968,
  },
  {
    album: "The Screaming End: The Best of Gene Vincent and His Blue Caps",
    artist: "Gene Vincent & His Blue Caps",
    rank: 103,
    title: "Be-Bop-A-Lula",
    year: 1956,
  },
  {
    album: "Bad Girls",
    artist: "Donna Summer",
    rank: 104,
    title: "Hot Stuff",
    year: 1979,
  },
  {
    album: "Innervisions",
    artist: "Stevie Wonder",
    rank: 105,
    title: "Living For The City",
    year: 1973,
  },
  {
    album: "Bridge Over Troubled Water",
    artist: "Simon & Garfunkel",
    rank: 106,
    title: "The Boxer",
    year: 1969,
  },
  {
    album: "Bringing It All Back Home",
    artist: "Bob Dylan",
    rank: 107,
    title: "Mr. Tambourine Man",
    year: 1965,
  },
  {
    album: "Greatest Hits",
    artist: "Buddy Holly & The Crickets",
    rank: 108,
    title: "Not Fade Away",
    year: 1957,
  },
  {
    album: "1999",
    artist: "Prince",
    rank: 109,
    title: "Little Red Corvette",
    year: 1983,
  },
  {
    album: "Blowin' Your Mind",
    artist: "Van Morrison",
    rank: 110,
    title: "Brown Eyed Girl",
    year: 1967,
  },
  {
    album: "Otis Blue: Otis Redding Sings Soul",
    artist: "Otis Redding",
    rank: 111,
    title: "I've Been Loving You Too Long (To Stop Now)",
    year: 1965,
  },
  {
    album: "The Ultimate Collection",
    artist: "Hank Williams",
    rank: 112,
    title: "I'm So Lonesome I Could Cry",
    year: 1949,
  },
  {
    album: "Sunrise",
    artist: "Elvis Presley",
    rank: 113,
    title: "That's All Right",
    year: 1954,
  },
  {
    album: "The Very Best of the Drifters",
    artist: "The Drifters",
    rank: 114,
    title: "Up On the Roof",
    year: 1962,
  },
  {
    album: "Greatest Hits",
    artist: "Sam Cooke",
    rank: 115,
    title: "You Send Me",
    year: 1957,
  },
  {
    album: "Let It Bleed",
    artist: "The Rolling Stones",
    rank: 116,
    title: "Honky Tonk Women",
    year: 1969,
  },
  {
    album: "Al Green Explores Your Mind",
    artist: "Al Green",
    rank: 117,
    title: "Take Me To The River",
    year: 1974,
  },
  {
    album: "Dangerously in Love",
    artist: "Beyoncé",
    rank: 118,
    title: "Crazy in Love (feat.  Jay-Z)",
    year: 2003,
  },
  {
    album: "The Isley Brothers Story, Vol. 1: Rockin' Soul",
    artist: "The Isley Brothers",
    rank: 119,
    title: "Shout (Parts 1 & 2)",
    year: 1959,
  },
  {
    album: "Rumours",
    artist: "Fleetwood Mac",
    rank: 120,
    title: "Go Your Own Way",
    year: 1977,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Jackson 5",
    rank: 121,
    title: "I Want You Back",
    year: 1969,
  },
  {
    album: "The Very Best of Ben E. King",
    artist: "Ben E. King",
    rank: 122,
    title: "Stand By Me",
    year: 1961,
  },
  {
    album: "The Best of the Animals",
    artist: "The Animals",
    rank: 123,
    title: "The House of the Rising Sun",
    year: 1964,
  },
  {
    album: "50th Anniversary Collection",
    artist: "James Brown",
    rank: 124,
    title: "It's A Man's Man's Man's World",
    year: 1966,
  },
  {
    album: "Forty Licks",
    artist: "The Rolling Stones",
    rank: 125,
    title: "Jumpin' Jack Flash",
    year: 1968,
  },
  {
    album: "Girl Group Greats",
    artist: "The Shirelles",
    rank: 126,
    title: "Will You Love Me Tomorrow",
    year: 1960,
  },
  {
    album: "The Very Best of Big Joe Turner",
    artist: "Big Joe Turner",
    rank: 127,
    title: "Shake",
    year: 1954,
  },
  {
    album: "Hunky Dory",
    artist: "David Bowie",
    rank: 128,
    title: "Changes",
    year: 1971,
  },
  {
    album: "Johnny B. Goode: His Complete '50s Chess Recordings",
    artist: "Chuck Berry",
    rank: 129,
    title: "Rock and Roll Music",
    year: 1957,
  },
  {
    album: "Steppenwolf",
    artist: "Steppenwolf",
    rank: 130,
    title: "Born to Be Wild",
    year: 1968,
  },
  {
    album: "Every Picture Tells A Story",
    artist: "Rod Stewart",
    rank: 131,
    title: "Maggie May",
    year: 1971,
  },
  {
    album: "The Joshua Tree",
    artist: "U2",
    rank: 132,
    title: "With or Without You",
    year: 1987,
  },
  {
    album: "His Best: The Chess 50th Anniversary Collection",
    artist: "Bo Diddley",
    rank: 133,
    title: "Who Do You Love?",
    year: 1957,
  },
  {
    album: "Who's Next",
    artist: "The Who",
    rank: 134,
    title: "Won't Get Fooled Again",
    year: 1971,
  },
  {
    album: "The Very Best of Wilson Pickett",
    artist: "Wilson Pickett",
    rank: 135,
    title: "In the Midnight Hour",
    year: 1965,
  },
  {
    album: "The Beatles",
    artist: "The Beatles",
    rank: 136,
    title: "While My Guitar Gently Weeps",
    year: 1968,
  },
  {
    album: "Greatest Hits",
    artist: "Elton John",
    rank: 137,
    title: "Your Song",
    year: 1970,
  },
  {
    album: "Revolver",
    artist: "The Beatles",
    rank: 138,
    title: "Eleanor Rigby",
    year: 1966,
  },
  {
    album: "There's a Riot Goin' On",
    artist: "Sly & The Family Stone",
    rank: 139,
    title: "Family Affair",
    year: 1971,
  },
  {
    album: "Please Please Me",
    artist: "The Beatles",
    rank: 140,
    title: "I Saw Her Standing There",
    year: 1964,
  },
  {
    album: "Physical Graffiti",
    artist: "Led Zeppelin",
    rank: 141,
    title: "Kashmir",
    year: 1975,
  },
  {
    album: "All-Time Original Hits",
    artist: "The Everly Brothers",
    rank: 142,
    title: "All I Have to Do Is Dream",
    year: 1958,
  },
  {
    album: "50th Anniversary Collection",
    artist: "James Brown",
    rank: 143,
    title: "Please, Please, Please",
    year: 1956,
  },
  {
    album: "Purple Rain",
    artist: "Prince and The Revolution",
    rank: 144,
    title: "Purple Rain",
    year: 1984,
  },
  {
    album: "Road to Ruin",
    artist: "Ramones",
    rank: 145,
    title: "I Wanna Be Sedated",
    year: 1978,
  },
  {
    album: "Stand!",
    artist: "Sly & The Family Stone",
    rank: 146,
    title: "Everyday People",
    year: 1968,
  },
  {
    album: "The B-52's",
    artist: "The B-52's",
    rank: 147,
    title: "Rock Lobster",
    year: 1979,
  },
  {
    album: "Pearl",
    artist: "Janis Joplin",
    rank: 148,
    title: "Me And Bobby McGee",
    year: 1971,
  },
  {
    album: "Lust For Life",
    artist: "Iggy Pop",
    rank: 149,
    title: "Lust For Life",
    year: 1977,
  },
  {
    album: "All-Time Original Hits",
    artist: "The Everly Brothers",
    rank: 150,
    title: "Cathy's Clown",
    year: 1960,
  },
  {
    album: "Fifth Dimension",
    artist: "The Byrds",
    rank: 151,
    title: "Eight Miles High",
    year: 1966,
  },
  {
    album: "Earth Angel",
    artist: "The Penguins",
    rank: 152,
    title: "Earth Angel",
    year: 1954,
  },
  {
    album: "Are You Experienced?",
    artist: "The Jimi Hendrix Experience",
    rank: 153,
    title: "Foxey Lady",
    year: 1965,
  },
  {
    album: "A Hard Day's Night",
    artist: "The Beatles",
    rank: 154,
    title: "A Hard Day's Night",
    year: 1964,
  },
  {
    album: "Buddy Holly: Greatest Hits",
    artist: "Buddy Holly & The Crickets",
    rank: 155,
    title: "Rave On",
    year: 1958,
  },
  {
    album: "Bayou Country",
    artist: "Creedence Clearwater Revival",
    rank: 156,
    title: "Proud Mary",
    year: 1969,
  },
  {
    album: "Sounds of Silence",
    artist: "Simon & Garfunkel",
    rank: 157,
    title: "The Sound of Silence",
    year: 1965,
  },
  {
    album: "The Best of the Flamingos",
    artist: "The Flamingos",
    rank: 158,
    title: "I Only Have Eyes for You",
    year: 1959,
  },
  {
    album: "The Best of Bill Haley and His Comets",
    artist: "Bill Haley & His Comets",
    rank: 159,
    title: "(We're Gonna) Rock Around The Clock",
    year: 1954,
  },
  {
    album: "No Line on the Horizon",
    artist: "U2",
    rank: 160,
    title: "Moment of Surrender",
    year: 2009,
  },
  {
    album: "The Velvet Underground & Nico",
    artist: "The Velvet Underground",
    rank: 161,
    title: "I'm Waiting for the Man",
    year: 1967,
  },
  {
    album: "It Takes a Nation of Millions to Hold Us Back",
    artist: "Public Enemy",
    rank: 162,
    title: "Bring the Noise",
    year: 1988,
  },
  {
    album: "The Essential Johnny Cash",
    artist: "Johnny Cash",
    rank: 163,
    title: "Folsom Prison Blues",
    year: 1956,
  },
  {
    album: "Modern Sounds in Country and Western Music",
    artist: "Ray Charles",
    rank: 164,
    title: "I Can't Stop Loving You",
    year: 1962,
  },
  {
    album: "I Do Not Want What I Haven't Got",
    artist: "Sinead O'Connor",
    rank: 165,
    title: "Nothing Compares 2 U",
    year: 1990,
  },
  {
    album: "A Night at the Opera",
    artist: "Queen",
    rank: 166,
    title: "Bohemian Rhapsody",
    year: 1975,
  },
  {
    album: "Tracy Chapman",
    artist: "Tracy Chapman",
    rank: 167,
    title: "Fast Car",
    year: 1988,
  },
  {
    album: "Let's Get It On",
    artist: "Marvin Gaye",
    rank: 168,
    title: "Let's Get It On",
    year: 1973,
  },
  {
    album: "Anthology",
    artist: "The Temptations",
    rank: 169,
    title: "Papa Was a Rollin' Stone",
    year: 1972,
  },
  {
    album: "Out of Time",
    artist: "R.E.M.",
    rank: 170,
    title: "Losing My Religion",
    year: 1991,
  },
  {
    album: "Clouds",
    artist: "Joni Mitchell",
    rank: 171,
    title: "Both Sides Now",
    year: 1969,
  },
  {
    album: "The Black Album",
    artist: "Jay-Z",
    rank: 172,
    title: "99 Problems",
    year: 2004,
  },
  {
    album: "Aerosmith",
    artist: "Aerosmith",
    rank: 173,
    title: "Dream On",
    year: 1973,
  },
  {
    album: "Arrival",
    artist: "ABBA",
    rank: 174,
    title: "Dancing Queen",
    year: 1976,
  },
  {
    album: "Never Mind the Bollocks, Here's the Sex Pistols",
    artist: "Sex Pistols",
    rank: 175,
    title: "God Save the Queen",
    year: 1977,
  },
  {
    album: "Aftermath",
    artist: "The Rolling Stones",
    rank: 176,
    title: "Paint It, Black",
    year: 1966,
  },
  {
    album: "I Fought the Law: The Best of the Bobby Fuller Four",
    artist: "The Bobby Fuller Four",
    rank: 177,
    title: "I Fought the Law",
    year: 1966,
  },
  {
    album: "Sounds of Summer",
    artist: "The Beach Boys",
    rank: 178,
    title: "Don't Worry Baby",
    year: 1964,
  },
  {
    album: "Full Moon Fever",
    artist: "Tom Petty",
    rank: 179,
    title: "Free Fallin'",
    year: 1989,
  },
  {
    album: "Radio City",
    artist: "Big Star",
    rank: 180,
    title: "September Gurls",
    year: 1974,
  },
  {
    album: "Substance 1977-1980",
    artist: "Joy Division",
    rank: 181,
    title: "Love Will Tear Us Apart",
    year: 1980,
  },
  {
    album: "Speakerboxxx/The Love Below",
    artist: "OutKast",
    rank: 182,
    title: "Hey Ya!",
    year: 2003,
  },
  {
    album: "Green Onions",
    artist: "Booker T. & The MG's",
    rank: 183,
    title: "Green Onions",
    year: 1962,
  },
  {
    album: "The Drifters' Golden Hits",
    artist: "The Drifters",
    rank: 184,
    title: "Save the Last Dance for Me",
    year: 1960,
  },
  {
    album: "Greatest Hits",
    artist: "B.B. King",
    rank: 185,
    title: "The Thrill Is Gone",
    year: 1969,
  },
  {
    album: "Please Please Me",
    artist: "The Beatles",
    rank: 186,
    title: "Please Please Me",
    year: 1964,
  },
  {
    album: "Highway 61 Revisited",
    artist: "Bob Dylan",
    rank: 187,
    title: "Desolation Row",
    year: 1965,
  },
  {
    album: "Cosmo's Factory",
    artist: "Creedence Clearwater Revival",
    rank: 188,
    title: "Who'll Stop the Rain",
    year: 1970,
  },
  {
    album: "I Never Loved a Man (the Way I Love You)",
    artist: "Aretha Franklin",
    rank: 189,
    title: "I Never Loved a Man (the Way I Love You)",
    year: 1967,
  },
  {
    album: "Back in Black",
    artist: "AC/DC",
    rank: 190,
    title: "Back in Black",
    year: 1980,
  },
  {
    album: "Saturday Night Fever",
    artist: "Bee Gees",
    rank: 191,
    title: "Stayin' Alive",
    year: 1977,
  },
  {
    album: "The Essential Bob Dylan",
    artist: "Bob Dylan",
    rank: 192,
    title: "Knocking On Heaven's Door",
    year: 1973,
  },
  {
    album: "One More From the Road",
    artist: "Lynyrd Skynyrd",
    rank: 193,
    title: "Free Bird",
    year: 1973,
  },
  {
    album: "Back to Black",
    artist: "Amy Winehouse",
    rank: 194,
    title: "Rehab",
    year: 2007,
  },
  {
    album: "Wichita Lineman",
    artist: "Glen Campbell",
    rank: 195,
    title: "Wichita Lineman",
    year: 1968,
  },
  {
    album: "The Very Best of the Drifters",
    artist: "The Drifters",
    rank: 196,
    title: "There Goes My Baby",
    year: 1959,
  },
  {
    album: "Greatest Hits",
    artist: "Buddy Holly",
    rank: 197,
    title: "Peggy Sue",
    year: 1957,
  },
  {
    album: "Appetite for Destruction",
    artist: "Guns N' Roses",
    rank: 198,
    title: "Sweet Child o' Mine",
    year: 1987,
  },
  {
    album: "The Best of the Chantels",
    artist: "The Chantels",
    rank: 199,
    title: "Maybe",
    year: 1957,
  },
  {
    album: "Elvis: 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 200,
    title: "Don't Be Cruel",
    year: 1956,
  },
  {
    album: "Are You Experienced?",
    artist: "The Jimi Hendrix Experience",
    rank: 201,
    title: "Hey Joe",
    year: 1966,
  },
  {
    album: "Funkentelechy vs. the Placebo Syndrome",
    artist: "Parliament",
    rank: 202,
    title: "Flash Light",
    year: 1977,
  },
  {
    album: "Mellow Gold",
    artist: "Beck",
    rank: 203,
    title: "Loser",
    year: 1993,
  },
  {
    album: "Substance",
    artist: "New Order",
    rank: 204,
    title: "Bizarre Love Triangle",
    year: 1986,
  },
  {
    album: "Abbey Road",
    artist: "The Beatles",
    rank: 205,
    title: "Come Together",
    year: 1969,
  },
  {
    album: "The Essential Bob Dylan",
    artist: "Bob Dylan",
    rank: 206,
    title: "Positively 4th Street",
    year: 1965,
  },
  {
    album: "Very Best of Otis Redding",
    artist: "Otis Redding",
    rank: 207,
    title: "Try a Little Tenderness",
    year: 1966,
  },
  {
    album: "Lean on Me",
    artist: "Bill Withers",
    rank: 208,
    title: "Lean on Me",
    year: 1972,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Four Tops",
    rank: 209,
    title: "Reach Out I'll Be There",
    year: 1966,
  },
  {
    album: "All-Time Original Hits",
    artist: "The Everly Brothers",
    rank: 210,
    title: "Bye Bye Love",
    year: 1957,
  },
  {
    album: "The Story of Them",
    artist: "Them",
    rank: 211,
    title: "Gloria",
    year: 1965,
  },
  {
    album: "Surfer Girl/Shut Down, Volume 2",
    artist: "The Beach Boys",
    rank: 212,
    title: "In My Room",
    year: 1963,
  },
  {
    album: "More Action",
    artist: "? and the Mysterians",
    rank: 213,
    title: "96 Tears",
    year: 1966,
  },
  {
    album: "Pet Sounds",
    artist: "The Beach Boys",
    rank: 214,
    title: "Caroline, No",
    year: 1966,
  },
  {
    album: "1999",
    artist: "Prince",
    rank: 215,
    title: "1999",
    year: 1982,
  },
  {
    album: "Freedom",
    artist: "Neil Young",
    rank: 216,
    title: "Rockin' in the Free World",
    year: 1989,
  },
  {
    album: "The Ultimate Collection",
    artist: "Hank Williams",
    rank: 217,
    title: "Your Cheatin' Heart",
    year: 1953,
  },
  {
    album: "Do You Believe in Magic",
    artist: "The Lovin' Spoonful",
    rank: 218,
    title: "Do You Believe In Magic",
    year: 1965,
  },
  {
    album: "Jolene",
    artist: "Dolly Parton",
    rank: 219,
    title: "Jolene",
    year: 1974,
  },
  {
    album: "The Very Best of John Lee Hooker",
    artist: "John Lee Hooker",
    rank: 220,
    title: "Boom Boom",
    year: 1963,
  },
  {
    album: "Anniversary Collection",
    artist: "Howlin' Wolf",
    rank: 221,
    title: "Spoonful",
    year: 1960,
  },
  {
    album: "There's Gonna Be a Storm",
    artist: "The Left Banke",
    rank: 222,
    title: "Walk away Renée",
    year: 1966,
  },
  {
    album: "Transformer",
    artist: "Lou Reed",
    rank: 223,
    title: "Walk on the Wild Side",
    year: 1972,
  },
  {
    album: "For the Lonely: 18 Greatest Hits",
    artist: "Roy Orbison",
    rank: 224,
    title: "Oh",
    year: 1964,
  },
  {
    album: "Dance to the Music",
    artist: "Sly & The Family Stone",
    rank: 225,
    title: "Dance To The Music",
    year: 1968,
  },
  {
    album: "The Anthology",
    artist: "Muddy Waters",
    rank: 226,
    title: "Hoochie Coochie Man",
    year: 1954,
  },
  {
    album: "Sweet Baby James",
    artist: "James Taylor",
    rank: 227,
    title: "Fire and Rain",
    year: 1970,
  },
  {
    album: "Combat Rock",
    artist: "The Clash",
    rank: 228,
    title: "Should I Stay or Should I Go",
    year: 1982,
  },
  {
    album: "Risqué",
    artist: "Chic",
    rank: 229,
    title: "Good Times",
    year: 1979,
  },
  {
    album: "The Anthology",
    artist: "Muddy Waters",
    rank: 230,
    title: "Mannish Boy",
    year: 1955,
  },
  {
    album: "Moondance",
    artist: "Van Morrison",
    rank: 231,
    title: "Moondance",
    year: 1970,
  },
  {
    album: "Blonde on Blonde",
    artist: "Bob Dylan",
    rank: 232,
    title: "Just Like a Woman",
    year: 1966,
  },
  {
    album: "Midnight Love",
    artist: "Marvin Gaye",
    rank: 233,
    title: "Sexual Healing",
    year: 1982,
  },
  {
    album: "For the Lonely: 18 Greatest Hits",
    artist: "Roy Orbison",
    rank: 234,
    title: "Only the Lonely",
    year: 1960,
  },
  {
    album: "Retrospective",
    artist: "The Animals",
    rank: 235,
    title: "We Gotta Get Out Of This Place",
    year: 1965,
  },
  {
    album: "Kala",
    artist: "M.I.A.",
    rank: 236,
    title: "Paper Planes",
    year: 2008,
  },
  {
    album: "Mr. Tambourine Man",
    artist: "The Byrds",
    rank: 237,
    title: "I'll Feel A Whole Lot Better",
    year: 1965,
  },
  {
    album: "Best of Buddy Holly",
    artist: "Buddy Holly & The Crickets",
    rank: 238,
    title: "Everyday",
    year: 1957,
  },
  {
    album: "Atlantic Singles",
    artist: "Ray Charles",
    rank: 239,
    title: "I Got a Woman",
    year: 1954,
  },
  {
    album: "Looking for the Perfect Beat 1980-1985",
    artist: "Afrika Bambaataa & the Soulsonic Force",
    rank: 240,
    title: "Planet Rock",
    year: 1982,
  },
  {
    album: "12 Greatest Hits",
    artist: "Patsy Cline",
    rank: 241,
    title: "I Fall to Pieces",
    year: 1961,
  },
  {
    album: "Dusty in Memphis",
    artist: "Dusty Springfield",
    rank: 242,
    title: "Son of a Preacher Man",
    year: 1968,
  },
  {
    album: "Runaround Sue",
    artist: "Dion",
    rank: 243,
    title: "The Wanderer",
    year: 1961,
  },
  {
    album: "Stand!",
    artist: "Sly & The Family Stone",
    rank: 244,
    title: "Stand!",
    year: 1969,
  },
  {
    album: "Honky Chateau",
    artist: "Elton John",
    rank: 245,
    title: "Rocket Man (I Think It's Going To Be A Long, Long Time)",
    year: 1972,
  },
  {
    album: "Cosmic Thing",
    artist: "The B-52's",
    rank: 246,
    title: "Love Shack",
    year: 1989,
  },
  {
    album: "Gimme Some Lovin'",
    artist: "The Spencer Davis Group",
    rank: 247,
    title: "Gimme Some Lovin'",
    year: 1966,
  },
  {
    album: "The Very Best of Jackie Wilson",
    artist: "Jackie Wilson",
    rank: 248,
    title: "(Your Love Keeps Lifting Me) Higher And Higher",
    year: 1967,
  },
  {
    album: "The Band",
    artist: "The Band",
    rank: 249,
    title: "The Night They Drove Old Dixie Down",
    year: 1969,
  },
  {
    album: "Greatest Hits",
    artist: "Sly & The Family Stone",
    rank: 250,
    title: "Hot Fun In The Summertime",
    year: 1969,
  },
  {
    album: "Rappers Delight: The Best of Sugarhill Gang",
    artist: "The Sugarhill Gang",
    rank: 251,
    title: "Rapper's Delight",
    year: 1979,
  },
  {
    album: "Lady Soul",
    artist: "Aretha Franklin",
    rank: 252,
    title: "Chain Of Fools",
    year: 1967,
  },
  {
    album: "Paranoid",
    artist: "Black Sabbath",
    rank: 253,
    title: "Paranoid",
    year: 1970,
  },
  {
    album: "Greatest Hits",
    artist: "The Drifters",
    rank: 254,
    title: "Money Honey",
    year: 1953,
  },
  {
    album: "That’s All",
    artist: "Bobby Darin",
    rank: 255,
    title: "Mack the Knife",
    year: 1959,
  },
  {
    album: "All The Young Dudes",
    artist: "Mott the Hoople",
    rank: 256,
    title: "All the Young Dudes",
    year: 1972,
  },
  {
    album: "OK Computer",
    artist: "Radiohead",
    rank: 257,
    title: "Paranoid Android",
    year: 1997,
  },
  {
    album: "Highway to Hell",
    artist: "AC/DC",
    rank: 258,
    title: "Highway To Hell",
    year: 1979,
  },
  {
    album: "Parallel Lines",
    artist: "Blondie",
    rank: 259,
    title: "Heart of Glass",
    year: 1978,
  },
  {
    album: "Love and Theft",
    artist: "Bob Dylan",
    rank: 260,
    title: "Mississippi",
    year: 2001,
  },
  {
    album: "Greatest Hits",
    artist: "The Troggs",
    rank: 261,
    title: "Wild Thing",
    year: 1966,
  },
  {
    album: "The Who Sell Out",
    artist: "The Who",
    rank: 262,
    title: "I Can See for Miles",
    year: 1967,
  },
  {
    album: "Ultimate Collection",
    artist: "The Dells",
    rank: 263,
    title: "Oh",
    year: 1969,
  },
  {
    album: "Grace",
    artist: "Jeff Buckley",
    rank: 264,
    title: "Hallelujah",
    year: 1994,
  },
  {
    album: "Innervisions",
    artist: "Stevie Wonder",
    rank: 265,
    title: "Higher Ground",
    year: 1973,
  },
  {
    album: "Ooo Baby Baby: The Anthology",
    artist: "Smokey Robinson and the Miracles",
    rank: 266,
    title: "Ooo Baby Baby",
    year: 1965,
  },
  {
    album: "Best of the Crystals",
    artist: "The Crystals",
    rank: 267,
    title: "He's a Rebel",
    year: 1962,
  },
  {
    album: "Sail Away",
    artist: "Randy Newman",
    rank: 268,
    title: "Sail Away",
    year: 1972,
  },
  {
    album: "The Best of the Ronettes",
    artist: "The Ronettes",
    rank: 269,
    title: "Walking In The Rain",
    year: 1964,
  },
  {
    album: "Tightening It Up: The Best of Archie Bell and the Drells",
    artist: "Archie Bell & The Drells",
    rank: 270,
    title: "Tighten Up",
    year: 1968,
  },
  {
    album: "New York Dolls",
    artist: "New York Dolls",
    rank: 271,
    title: "Personality Crisis",
    year: 1973,
  },
  {
    album: "War",
    artist: "U2",
    rank: 272,
    title: "Sunday Bloody Sunday",
    year: 1983,
  },
  {
    album: "The College Dropout",
    artist: "Kanye West",
    rank: 273,
    title: "Jesus Walks",
    year: 2004,
  },
  {
    album: "The Modern Lovers",
    artist: "The Modern Lovers",
    rank: 274,
    title: "Roadrunner",
    year: 1976,
  },
  {
    album: "I Am What I Am",
    artist: "George Jones",
    rank: 275,
    title: "He Stopped Loving Her Today",
    year: 1980,
  },
  {
    album: "Pet Sounds",
    artist: "The Beach Boys",
    rank: 276,
    title: "Sloop John B",
    year: 1966,
  },
  {
    album: "The Anthology",
    artist: "Chuck Berry",
    rank: 277,
    title: "Sweet Little Sixteen",
    year: 1958,
  },
  {
    album: "Abbey Road",
    artist: "The Beatles",
    rank: 278,
    title: "Something",
    year: 1969,
  },
  {
    album: "Surrealistic Pillow",
    artist: "Jefferson Airplane",
    rank: 279,
    title: "Somebody to Love",
    year: 1967,
  },
  {
    album: "Born in the U.S.A.",
    artist: "Bruce Springsteen",
    rank: 280,
    title: "Born in the U.S.A.",
    year: 1984,
  },
  {
    album: "Bealtitude: Respect Yourself",
    artist: "The Staple Singers",
    rank: 281,
    title: "I'll Take You There",
    year: 1972,
  },
  {
    album: "The Rise and Fall of Ziggy Stardust and the Spiders Mars",
    artist: "David Bowie",
    rank: 282,
    title: "Ziggy Stardust",
    year: 1972,
  },
  {
    album: "Disintegration",
    artist: "The Cure",
    rank: 283,
    title: "Pictures of You",
    year: 1989,
  },
  {
    album: "The Best of the Girl Groups, Vol. 1",
    artist: "The Dixie Cups",
    rank: 284,
    title: "Chapel Of Love",
    year: 1964,
  },
  {
    album: "Lean on Me: The Best of Bill Withers",
    artist: "Bill Withers",
    rank: 285,
    title: "Ain't No Sunshine",
    year: 1971,
  },
  {
    album: "Elephant",
    artist: "The White Stripes",
    rank: 286,
    title: "Seven Nation Army",
    year: 2003,
  },
  {
    album: "Talking Book",
    artist: "Stevie Wonder",
    rank: 287,
    title: "You Are the Sunshine of My Life",
    year: 1972,
  },
  {
    album: "Court and Spark",
    artist: "Joni Mitchell",
    rank: 288,
    title: "Help Me",
    year: 1974,
  },
  {
    album: "Best of Blondie",
    artist: "Blondie",
    rank: 289,
    title: "Call Me",
    year: 1980,
  },
  {
    album: "Armed Forces",
    artist: "Elvis Costello & The Attractions",
    rank: 290,
    title: "(What's So Funny 'Bout) Peace, Love And Understanding",
    year: 1979,
  },
  {
    album: "His Best",
    artist: "Howlin' Wolf",
    rank: 291,
    title: "Smokestack Lightning",
    year: 1965,
  },
  {
    album: "Slanted and Enchanted",
    artist: "Pavement",
    rank: 292,
    title: "Summer Babe (Winter Version)",
    year: 1992,
  },
  {
    album: "Raising Hell",
    artist: "Run-D.M.C.",
    rank: 293,
    title: "Walk This Way",
    year: 1986,
  },
  {
    album: "Motown: The Classic Years",
    artist: "Barrett Strong",
    rank: 294,
    title: "Money (That's What I Want)",
    year: 1960,
  },
  {
    album: "A Hard Day's Night",
    artist: "The Beatles",
    rank: 295,
    title: "Can't Buy Me Love",
    year: 1964,
  },
  {
    album: "The Marshall Mathers LP",
    artist: "Eminem",
    rank: 296,
    title: "Stan (feat. Dido)",
    year: 2000,
  },
  {
    album: "British Invasion: 1963-1967",
    artist: "The Zombies",
    rank: 297,
    title: "She's Not There",
    year: 1964,
  },
  {
    album: "London Calling",
    artist: "The Clash",
    rank: 298,
    title: "Train in Vain",
    year: 1979,
  },
  {
    album: "Greatest Hits",
    artist: "Al Green",
    rank: 299,
    title: "Tired Of Being Alone",
    year: 1971,
  },
  {
    album: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    rank: 300,
    title: "Black Dog",
    year: 1971,
  },
  {
    album: "Beggars Banquet",
    artist: "The Rolling Stones",
    rank: 301,
    title: "Street Fighting Man",
    year: 1968,
  },
  {
    album: "Legend",
    artist: "Bob Marley & The Wailers",
    rank: 302,
    title: "Get Up, Stand Up",
    year: 1975,
  },
  {
    album: "Harvest",
    artist: "Neil Young",
    rank: 303,
    title: "Heart of Gold",
    year: 1972,
  },
  {
    album: "Sign 'O' The Times",
    artist: "Prince",
    rank: 304,
    title: "Sign 'O' The Times",
    year: 1987,
  },
  {
    album: "Parallel Lines",
    artist: "Blondie",
    rank: 305,
    title: "One Way or Another",
    year: 1978,
  },
  {
    album: "Like a Prayer",
    artist: "Madonna",
    rank: 306,
    title: "Like a Prayer",
    year: 1989,
  },
  {
    album: "Discovery",
    artist: "Daft Punk",
    rank: 307,
    title: "One More Time",
    year: 2000,
  },
  {
    album: "Blondes Have More Fun",
    artist: "Rod Stewart",
    rank: 308,
    title: "Da Ya Think I'm Sexy?",
    year: 1978,
  },
  {
    album: "Red Headed Stranger",
    artist: "Willie Nelson",
    rank: 309,
    title: "Blue Eyes Crying In The Rain",
    year: 1975,
  },
  {
    album: "Between the Buttons",
    artist: "The Rolling Stones",
    rank: 310,
    title: "Ruby Tuesday",
    year: 1967,
  },
  {
    album: "Sgt. Pepper's Lonely Hearts Club Band",
    artist: "The Beatles",
    rank: 311,
    title: "With a Little Help My Friends",
    year: 1967,
  },
  {
    album: "50th Anniversary Collection",
    artist: "James Brown",
    rank: 312,
    title: "Say It Loud (I'm Black and I'm Proud)",
    year: 1968,
  },
  {
    album: "Sound Affects",
    artist: "The Jam",
    rank: 313,
    title: "That's Entertainment",
    year: 1980,
  },
  {
    album: "The Best of Frankie Lymon and the Teenagers",
    artist: "Frankie Lymon & The Teenagers",
    rank: 314,
    title: "Why Do Fools Fall In Love",
    year: 1956,
  },
  {
    album: "The Greatest Hits of Jackie Wilson",
    artist: "Jackie Wilson",
    rank: 315,
    title: "Lonely Teardrops",
    year: 1958,
  },
  {
    album: "Private Dancer",
    artist: "Tina Turner",
    rank: 316,
    title: "What's Love Got to Do With It",
    year: 1984,
  },
  {
    album: "Paranoid",
    artist: "Black Sabbath",
    rank: 317,
    title: "Iron Man",
    year: 1971,
  },
  {
    album: "The Best of the Everly Brothers",
    artist: "The Everly Brothers",
    rank: 318,
    title: "Wake Up Little Susie",
    year: 1957,
  },
  {
    album: "For the Lonely: 18 Greatest Hits",
    artist: "Roy Orbison",
    rank: 319,
    title: "In Dreams",
    year: 1963,
  },
  {
    album: "Voodoo Jive",
    artist: "Screamin' Jay Hawkins",
    rank: 320,
    title: "I Put A Spell On You",
    year: 1956,
  },
  {
    album: "The Wall",
    artist: "Pink Floyd",
    rank: 321,
    title: "Comfortably Numb",
    year: 1979,
  },
  {
    album: "Retrospective",
    artist: "The Animals",
    rank: 322,
    title: "Don't Let Me Be Misunderstood",
    year: 1965,
  },
  {
    album: "My Aim Is True",
    artist: "Elvis Costello",
    rank: 323,
    title: "Alison",
    year: 1977,
  },
  {
    album: "Wish You Were Here",
    artist: "Pink Floyd",
    rank: 324,
    title: "Wish You Were Here",
    year: 1975,
  },
  {
    album: "Wonderful World, Beautiful People",
    artist: "Jimmy Cliff",
    rank: 325,
    title: "Many Rivers to Cross",
    year: 1969,
  },
  {
    album: "School's Out",
    artist: "Alice Cooper",
    rank: 326,
    title: "School's Out",
    year: 1972,
  },
  {
    album: "Franz Ferdinand",
    artist: "Franz Ferdinand",
    rank: 327,
    title: "Take Me Out",
    year: 2004,
  },
  {
    album: "Led Zeppelin II",
    artist: "Led Zeppelin",
    rank: 328,
    title: "Heartbreaker",
    year: 1969,
  },
  {
    album: "Zuma",
    artist: "Neil Young & Crazy Horse",
    rank: 329,
    title: "Cortez the Killer",
    year: 1975,
  },
  {
    album: "Fear of a Black Planet",
    artist: "Public Enemy",
    rank: 330,
    title: "Fight the Power",
    year: 1989,
  },
  {
    album: "Wave",
    artist: "Patti Smith Group",
    rank: 331,
    title: "Dancing Barefoot",
    year: 1979,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Supremes",
    rank: 332,
    title: "Baby Love",
    year: 1964,
  },
  {
    album: "The Very Best of the Rascals",
    artist: "The Rascals",
    rank: 333,
    title: "Good Lovin'",
    year: 1966,
  },
  {
    album: "50th Anniversary Collection",
    artist: "James Brown",
    rank: 334,
    title: "Get Up (I Feel Like Being a) Sex Machine",
    year: 1970,
  },
  {
    album: "Greatest Hits",
    artist: "The Impressions",
    rank: 335,
    title: "For Your Precious Love",
    year: 1958,
  },
  {
    album: "The Doors",
    artist: "The Doors",
    rank: 336,
    title: "The End",
    year: 1967,
  },
  {
    album: "That's The Way of the World",
    artist: "Earth",
    rank: 337,
    title: "Wind and Fire",
    year: 1975,
  },
  {
    album: "News of the World",
    artist: "Queen",
    rank: 338,
    title: "We Will Rock You",
    year: 1977,
  },
  {
    album: "Luck of the Draw",
    artist: "Bonnie Raitt",
    rank: 339,
    title: "I Can't Make You Love Me",
    year: 1991,
  },
  {
    album: "Bringing It All Back Home",
    artist: "Bob Dylan",
    rank: 340,
    title: "Subterranean Homesick Blues",
    year: 1965,
  },
  {
    album: "Spirit in the Sky",
    artist: "Norman Greenbaum",
    rank: 341,
    title: "Spirit in the Sky",
    year: 1970,
  },
  {
    album: "Loaded (Fully Loaded Edition)",
    artist: "The Velvet Underground",
    rank: 342,
    title: "Sweet Jane",
    year: 1970,
  },
  {
    album: "Sticky Fingers",
    artist: "The Rolling Stones",
    rank: 343,
    title: "Wild Horses",
    year: 1971,
  },
  {
    album: "Thriller",
    artist: "Michael Jackson",
    rank: 344,
    title: "Beat It",
    year: 1982,
  },
  {
    album: "All That You Can't Leave Behind",
    artist: "U2",
    rank: 345,
    title: "Beautiful Day",
    year: 2000,
  },
  {
    album: "Toys in the Attic",
    artist: "Aerosmith",
    rank: 346,
    title: "Walk This Way",
    year: 1975,
  },
  {
    album: "McCartney",
    artist: "Paul McCartney",
    rank: 347,
    title: "Maybe I'm Amazed",
    year: 1970,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Supremes",
    rank: 348,
    title: "You Keep Me Hangin' On",
    year: 1966,
  },
  {
    album: "Who's Next",
    artist: "The Who",
    rank: 349,
    title: "Baba O'Riley",
    year: 1971,
  },
  {
    album: "The Harder They Come",
    artist: "Jimmy Cliff",
    rank: 350,
    title: "The Harder They Come",
    year: 1975,
  },
  {
    album: "Runaround Sue",
    artist: "Dion",
    rank: 351,
    title: "Runaround Sue",
    year: 1961,
  },
  {
    album: "Soul on Fire: The Best of LaVern Baker",
    artist: "Lavern Baker",
    rank: 352,
    title: "Jim Dandy",
    year: 1956,
  },
  {
    album: "Cheap Thrills",
    artist: "Big Brother & The Holding Company",
    rank: 353,
    title: "Piece of My Heart",
    year: 1968,
  },
  {
    album: "The Ritchie Valens Story",
    artist: "Ritchie Valens",
    rank: 354,
    title: "La Bamba",
    year: 1958,
  },
  {
    album: "Greatest Hits",
    artist: "2Pac",
    rank: 355,
    title: "California Love (remix) (feat. Dr. Dre & Roger Troutman)",
    year: 1996,
  },
  {
    album: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    rank: 356,
    title: "Candle in the Wind",
    year: 1973,
  },
  {
    album: "The Essential Isley Brothers",
    artist: "The Isley Brothers",
    rank: 357,
    title: "That Lady (Parts 1 & 2)",
    year: 1973,
  },
  {
    album: "The Very Best of Ben E. King",
    artist: "Ben E. King",
    rank: 358,
    title: "Spanish Harlem",
    year: 1960,
  },
  {
    album: "The Loco-Motion",
    artist: "Little Eva",
    rank: 359,
    title: "The Loco-Motion",
    year: 1962,
  },
  {
    album: "The Magic Touch: An Anthology",
    artist: "The Platters",
    rank: 360,
    title: "The Great Pretender",
    year: 1955,
  },
  {
    album: "Elvis 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 361,
    title: "All Shook Up",
    year: 1957,
  },
  {
    album: '"Rush" Soundtrack',
    artist: "Eric Clapton",
    rank: 362,
    title: "Tears in Heaven",
    year: 1992,
  },
  {
    album: "My Aim Is True",
    artist: "Elvis Costello",
    rank: 363,
    title: "Watching The Detectives",
    year: 1977,
  },
  {
    album: "Green River",
    artist: "Creedence Clearwater Revival",
    rank: 364,
    title: "Bad Moon Rising",
    year: 1969,
  },
  {
    album: "Sweet Dreams",
    artist: "Eurythmics",
    rank: 365,
    title: "Sweet Dreams (Are Made of This)",
    year: 1983,
  },
  {
    album: "Axis: Bold As Love",
    artist: "The Jimi Hendrix Experience",
    rank: 366,
    title: "Little Wing",
    year: 1968,
  },
  {
    album: "The Ultimate Collection",
    artist: "Martha and the Vandellas",
    rank: 367,
    title: "Nowhere To Run",
    year: 1965,
  },
  {
    album: "The Anthology",
    artist: "Muddy Waters",
    rank: 368,
    title: "Got My Mojo Working",
    year: 1957,
  },
  {
    album: "Killing Me Softly",
    artist: "Roberta Flack",
    rank: 369,
    title: "Killing Me Softly With His Song",
    year: 1973,
  },
  {
    album: "Magical Mystery Tour",
    artist: "The Beatles",
    rank: 370,
    title: "All You Need Is Love",
    year: 1967,
  },
  {
    album: "The Clash",
    artist: "The Clash",
    rank: 371,
    title: "Complete Control",
    year: 1979,
  },
  {
    album: "The Letter",
    artist: "The Box Tops",
    rank: 372,
    title: "The Letter",
    year: 1967,
  },
  {
    album: "Highway 61 Revisited",
    artist: "Bob Dylan",
    rank: 373,
    title: "Highway 61 Revisited",
    year: 1965,
  },
  {
    album: "Anthology 1962-1974",
    artist: "The Righteous Brothers",
    rank: 374,
    title: "Unchained Melody",
    year: 1965,
  },
  {
    album: "Saturday Night Fever",
    artist: "Bee Gees",
    rank: 375,
    title: "How Deep Is Your Love",
    year: 1977,
  },
  {
    album: "Wheels Of Fire",
    artist: "Cream",
    rank: 376,
    title: "White Room",
    year: 1968,
  },
  {
    album: "Violator",
    artist: "Depeche Mode",
    rank: 377,
    title: "Personal Jesus",
    year: 1989,
  },
  {
    album: "His Best: The Chess 50th Anniversary Collection",
    artist: "Bo Diddley",
    rank: 378,
    title: "I'm A Man",
    year: 1955,
  },
  {
    album: "Are You Experienced?",
    artist: "The Jimi Hendrix Experience",
    rank: 379,
    title: "The Wind Cries Mary",
    year: 1967,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Who",
    rank: 380,
    title: "I Can't Explain",
    year: 1965,
  },
  {
    album: "Marquee Moon",
    artist: "Television",
    rank: 381,
    title: "Marquee Moon",
    year: 1977,
  },
  {
    album: "Portrait of a Legend 1951-1964",
    artist: "Sam Cooke",
    rank: 382,
    title: "Wonderful World",
    year: 1960,
  },
  {
    album: "The Anthology",
    artist: "Chuck Berry",
    rank: 383,
    title: "Brown Eyed Handsome Man",
    year: 1956,
  },
  {
    album: "The Wall",
    artist: "Pink Floyd",
    rank: 384,
    title: "Another Brick In The Wall (Part II)",
    year: 1979,
  },
  {
    album: "The Bends",
    artist: "Radiohead",
    rank: 385,
    title: "Fake Plastic Trees",
    year: 1995,
  },
  {
    album: "Fever to Tell",
    artist: "Yeah Yeah Yeahs",
    rank: 386,
    title: "Maps",
    year: 2004,
  },
  {
    album: "Ultimate Hits Collection",
    artist: "Ray Charles",
    rank: 387,
    title: "Hit the Road Jack",
    year: 1961,
  },
  {
    album: "The Unforgettable Fire",
    artist: "U2",
    rank: 388,
    title: "Pride (in the Name of Love)",
    year: 1984,
  },
  {
    album: "Murmur",
    artist: "R.E.M.",
    rank: 389,
    title: "Radio Free Europe",
    year: 1983,
  },
  {
    album: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    rank: 390,
    title: "Goodbye Yellow Brick Road",
    year: 1973,
  },
  {
    album: "Tell It Like It Is: Golden Classics",
    artist: "Aaron Neville",
    rank: 391,
    title: "Tell It Like It Is",
    year: 1965,
  },
  {
    album: "Urban Hymns",
    artist: "The Verve",
    rank: 392,
    title: "Bitter Sweet Symphony",
    year: 1997,
  },
  {
    album: "At Fillmore East",
    artist: "The Allman Brothers Band",
    rank: 393,
    title: "Whipping Post",
    year: 1971,
  },
  {
    album: "Help!",
    artist: "The Beatles",
    rank: 394,
    title: "Ticket to Ride",
    year: 1965,
  },
  {
    album: "Decade",
    artist: "Crosby",
    rank: 395,
    title: "Stills, Nash & Young",
    year: 1970,
  },
  {
    album: "Paid In Full",
    artist: "Eric B. & Rakim",
    rank: 396,
    title: "I Know You Got Soul",
    year: 1987,
  },
  {
    album: "Madman Across the Water",
    artist: "Elton John",
    rank: 397,
    title: "Tiny Dancer",
    year: 1972,
  },
  {
    album: "Outlandos d'Amour",
    artist: "The Police",
    rank: 398,
    title: "Roxanne",
    year: 1978,
  },
  {
    album: "Anthology",
    artist: "The Temptations",
    rank: 399,
    title: "Just My Imagination (Running Away With Me)",
    year: 1971,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Four Tops",
    rank: 400,
    title: "Baby I Need Your Loving",
    year: 1965,
  },
  {
    album: "The Lovin' Spoonful Greatest Hits",
    artist: "The Lovin' Spoonful",
    rank: 401,
    title: "Summer in the City",
    year: 1966,
  },
  {
    album: "Soul Hits of the '70s: Didn't It Blow Your Mind! Vol. 2",
    artist: "The Five Stairsteps",
    rank: 402,
    title: "O-o-h Child",
    year: 1970,
  },
  {
    album: "Elvis 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 403,
    title: "Can't Help Falling in Love",
    year: 1961,
  },
  {
    album: "The Best of the Shangri-Las",
    artist: "The Shangri-Las",
    rank: 404,
    title: "Remember (Walkin' In The Sand)",
    year: 1964,
  },
  {
    album: "Agents of Fortune",
    artist: "Blue Öyster Cult",
    rank: 405,
    title: "(Don't Fear) The Reaper",
    year: 1976,
  },
  {
    album: "#1 Record/Radio City",
    artist: "Big Star",
    rank: 406,
    title: "Thirteen",
    year: 1972,
  },
  {
    album: "Second Helping",
    artist: "Lynyrd Skynyrd",
    rank: 407,
    title: "Sweet Home Alabama",
    year: 1974,
  },
  {
    album: "Metallica",
    artist: "Metallica",
    rank: 408,
    title: "Enter Sandman",
    year: 1991,
  },
  {
    album: "25 All-Time Greatest Hits",
    artist: "The Shirelles",
    rank: 409,
    title: "Tonight's the Night",
    year: 1960,
  },
  {
    album: "Greatest Hits",
    artist: "Sly & The Family Stone",
    rank: 410,
    title: "Thank You (Falettinme Be Mice Elf Agin)",
    year: 1970,
  },
  {
    album: "Anthology",
    artist: "Eddie Cochran",
    rank: 411,
    title: "C'mon Everybody",
    year: 1958,
  },
  {
    album: "Good Girl Gone Bad",
    artist: "Rihanna",
    rank: 412,
    title: "Umbrella (feat. Jay-Z)",
    year: 2007,
  },
  {
    album: "Blonde on Blonde",
    artist: "Bob Dylan",
    rank: 413,
    title: "Visions of Johanna",
    year: 1966,
  },
  {
    album: "Singles 1969-1981",
    artist: "Carpenters",
    rank: 414,
    title: "We've Only Just Begun",
    year: 1971,
  },
  {
    album: "Nevermind",
    artist: "Nirvana",
    rank: 415,
    title: "In Bloom",
    year: 1991,
  },
  {
    album: "Toys in the Attic",
    artist: "Aerosmith",
    rank: 416,
    title: "Sweet Emotion",
    year: 1975,
  },
  {
    album: "Doolittle",
    artist: "Pixies",
    rank: 417,
    title: "Monkey Gone to Heaven",
    year: 1989,
  },
  {
    album: "The Donna Summer Anthology",
    artist: "Donna Summer",
    rank: 418,
    title: "I Feel Love",
    year: 1977,
  },
  {
    album: "Greatest Hits",
    artist: "Bobbie Gentry",
    rank: 419,
    title: "Ode to Billie Joe",
    year: 1967,
  },
  {
    album: "The Georgia Peach",
    artist: "Little Richard",
    rank: 420,
    title: "The Girl Can't Help It",
    year: 1957,
  },
  {
    album: "The Very Best of the Coasters",
    artist: "The Coasters",
    rank: 421,
    title: "Young Blood",
    year: 1957,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Four Tops",
    rank: 422,
    title: "I Can't Help Myself",
    year: 1965,
  },
  {
    album: "Building the Perfect Beast",
    artist: "Don Henley",
    rank: 423,
    title: "The Boys Of Summer",
    year: 1984,
  },
  {
    album: "Ready to Die",
    artist: "The Notorious B.I.G",
    rank: 424,
    title: "Juicy",
    year: 1994,
  },
  {
    album: "Straight Outta Compton",
    artist: "N.W.A",
    rank: 425,
    title: "Fuck tha Police",
    year: 1988,
  },
  {
    album: "Crosby, Stills and Nash",
    artist: "Crosby",
    rank: 426,
    title: "Stills & Nash, Suite: Judy Blue Eyes",
    year: 1969,
  },
  {
    album: "The Chronic",
    artist: "Dr. Dre",
    rank: 427,
    title: "Nuthin' but a 'G' Thang",
    year: 1993,
  },
  {
    album: "The Ultimate Isley Brothers",
    artist: "The Isley Brothers",
    rank: 428,
    title: "It's Your Thing",
    year: 1969,
  },
  {
    album: "Piano Man",
    artist: "Billy Joel",
    rank: 429,
    title: "Piano Man",
    year: 1973,
  },
  {
    album: "2nd to None",
    artist: "Elvis Presley",
    rank: 430,
    title: "Blue Suede Shoes",
    year: 1956,
  },
  {
    album: "Louder Than Bombs",
    artist: "The Smiths",
    rank: 431,
    title: "William",
    year: 1984,
  },
  {
    album: "American Idiot",
    artist: "Green day",
    rank: 432,
    title: "American Idiot",
    year: 2004,
  },
  {
    album: "Exile on Main Street",
    artist: "The Rolling Stones",
    rank: 433,
    title: "Tumbling Dice",
    year: 1972,
  },
  {
    album: "Machine Head",
    artist: "Deep Purple",
    rank: 434,
    title: "Smoke on the Water",
    year: 1972,
  },
  {
    album: "War",
    artist: "U2",
    rank: 435,
    title: "New Year's Day",
    year: 1983,
  },
  {
    album: "The Very Best of Solomon Burke",
    artist: "Solomon Burke",
    rank: 436,
    title: "Everybody Needs Somebody To Love",
    year: 1964,
  },
  {
    album: "The Clash",
    artist: "The Clash",
    rank: 437,
    title: "(White Man) In Hammersmith Palais",
    year: 1978,
  },
  {
    album: "The Fats Domino Jukebox: 20 Greatest Hits",
    artist: "Fats Domino",
    rank: 438,
    title: "Ain't That a Shame",
    year: 1955,
  },
  {
    album: "Essential Collection",
    artist: "Gladys Knight & The Pips",
    rank: 439,
    title: "Midnight Train To Georgia",
    year: 1977,
  },
  {
    album: "Led Zeppelin II",
    artist: "Led Zeppelin",
    rank: 440,
    title: "Ramble On",
    year: 1969,
  },
  {
    album: "The Very Best of Wilson Pickett",
    artist: "Wilson Pickett",
    rank: 441,
    title: "Mustang Sally",
    year: 1966,
  },
  {
    album: "Forever Changes",
    artist: "Love",
    rank: 442,
    title: "Alone Again Or",
    year: 1967,
  },
  {
    album: "Some Girls",
    artist: "The Rolling Stones",
    rank: 443,
    title: "Beast of Burden",
    year: 1981,
  },
  {
    album: "Elvis: 30 #1 Hits",
    artist: "Elvis Presley",
    rank: 444,
    title: "Love Me Tender",
    year: 1956,
  },
  {
    album: "The Stooges",
    artist: "The Stooges",
    rank: 445,
    title: "I Wanna Be Your Dog",
    year: 1969,
  },
  {
    album: "Hot, Cool and Vicious",
    artist: "Salt-N-Pepa",
    rank: 446,
    title: "Push It",
    year: 1987,
  },
  {
    album: "Uh-Huh",
    artist: "John Mellencamp",
    rank: 447,
    title: "Pink Houses",
    year: 1984,
  },
  {
    album: "Get Rich or Die Tryin'",
    artist: "50 Cent",
    rank: 448,
    title: "In Da Club",
    year: 2003,
  },
  {
    album: "Golden Classics",
    artist: "The Del-Vikings",
    rank: 449,
    title: "Come Go With Me",
    year: 1957,
  },
  {
    album: "Burnin'",
    artist: "Bob Marley & The Wailers",
    rank: 450,
    title: "I Shot The Sheriff",
    year: 1973,
  },
  {
    album: "The Beat Goes On: The Best of Sonny and Cher",
    artist: "Sonny & Cher",
    rank: 451,
    title: "I Got You Babe",
    year: 1965,
  },
  {
    album: "Nevermind",
    artist: "Nirvana",
    rank: 452,
    title: "Come as You Are",
    year: 1992,
  },
  {
    album: "The Harder They Come",
    artist: "Toot and the Maytals",
    rank: 453,
    title: "Pressure Drop",
    year: 1968,
  },
  {
    album: "Myrmidons of Melodrama: Definitive Collection",
    artist: "The Shangri-Las",
    rank: 454,
    title: "Leader of the Pack",
    year: 1964,
  },
  {
    album: "The Velvet Underground & Nico",
    artist: "The Velvet Underground",
    rank: 455,
    title: "Heroin",
    year: 1967,
  },
  {
    album: "Magical Mystery Tour",
    artist: "The Beatles",
    rank: 456,
    title: "Penny Lane",
    year: 1967,
  },
  {
    album: "Greatest Hits",
    artist: "Chubby Checker",
    rank: 457,
    title: "The Twist",
    year: 1960,
  },
  {
    album: "Greatest Hits",
    artist: "Sam Cooke",
    rank: 458,
    title: "Cupid",
    year: 1961,
  },
  {
    album: "Appetite for Destruction",
    artist: "Guns N' Roses",
    rank: 459,
    title: "Paradise City",
    year: 1987,
  },
  {
    album: "All Things Must Pass",
    artist: "George Harrison",
    rank: 460,
    title: "My Sweet Lord",
    year: 1970,
  },
  {
    album: "Rocket to Russia",
    artist: "Ramones",
    rank: 461,
    title: "Sheena Is a Punk Rocker",
    year: 1977,
  },
  {
    album: "In Utero",
    artist: "Nirvana",
    rank: 462,
    title: "All Apologies",
    year: 1993,
  },
  {
    album: "Soul Men",
    artist: "Sam & Dave",
    rank: 463,
    title: "Soul Man",
    year: 1965,
  },
  {
    album: "Parade",
    artist: "Prince and The Revolution",
    rank: 464,
    title: "Kiss",
    year: 1986,
  },
  {
    album: "The Anthology: 1947-1972",
    artist: "Muddy Waters",
    rank: 465,
    title: "Rollin' Stone",
    year: 1948,
  },
  {
    album: "Miss E … So Addictive",
    artist: "Missy Elliott",
    rank: 466,
    title: "Get Ur Freak On",
    year: 2001,
  },
  {
    album: "Vol. 3: Life and Times of S. Carter",
    artist: "Jay-Z",
    rank: 467,
    title: "Big Pimpin' (feat. UGK)",
    year: 2000,
  },
  {
    album: "Bealtitude: Respect Yourself",
    artist: "The Staple Singers",
    rank: 468,
    title: "Respect Yourself",
    year: 1972,
  },
  {
    album: "Past Masters",
    artist: "The Beatles",
    rank: 469,
    title: "Rain",
    year: 1966,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Four Tops",
    rank: 470,
    title: "Standing In The Shadows Of Love",
    year: 1966,
  },
  {
    album: "Heaven Tonight",
    artist: "Cheap Trick",
    rank: 471,
    title: "Surrender",
    year: 1978,
  },
  {
    album: "Greatest Hits",
    artist: "Del Shannon",
    rank: 472,
    title: "Runaway",
    year: 1961,
  },
  {
    album: "Appetite for Destruction",
    artist: "Guns N' Roses",
    rank: 473,
    title: "Welcome to the Jungle",
    year: 1987,
  },
  {
    album: "Moondance",
    artist: "Van Morrison",
    rank: 474,
    title: "Into The Mystic",
    year: 1970,
  },
  {
    album: "The Ultimate Collection",
    artist: "The Supremes",
    rank: 475,
    title: "Where Did Our Love Go",
    year: 1964,
  },
  {
    album: "I Never Loved a Man the Way I Love You",
    artist: "Aretha Franklin",
    rank: 476,
    title: "Do Right Woman, Do Right Man",
    year: 1967,
  },
  {
    album: "Meat Is Murder",
    artist: "The Smiths",
    rank: 477,
    title: "How Soon Is Now?",
    year: 1984,
  },
  {
    album: "Is This It",
    artist: "The Strokes",
    rank: 478,
    title: "Last Nite",
    year: 2001,
  },
  {
    album: "Agent Provocateur",
    artist: "Foreigner",
    rank: 479,
    title: "I Want To Know What Love Is",
    year: 1984,
  },
  {
    album: "Ill Communication",
    artist: "Beastie Boys",
    rank: 480,
    title: "Sabotage",
    year: 1994,
  },
  {
    album: "Street Songs",
    artist: "Rick James",
    rank: 481,
    title: "Super Freak",
    year: 1981,
  },
  {
    album: "Breakaway",
    artist: "Kelly Clarkson",
    rank: 482,
    title: "Since U Been Gone",
    year: 2004,
  },
  {
    album: "Surrealistic Pillow",
    artist: "Jefferson Airplane",
    rank: 483,
    title: "White Rabbit",
    year: 1967,
  },
  {
    album: "Justified",
    artist: "Justin Timberlake",
    rank: 484,
    title: "Cry Me a River",
    year: 2002,
  },
  {
    album: "Nightbirds",
    artist: "Labelle",
    rank: 485,
    title: "Lady Marmalade",
    year: 1974,
  },
  {
    album: "Young Americans",
    artist: "David Bowie",
    rank: 486,
    title: "Young Americans",
    year: 1975,
  },
  {
    album: "Love It to Death",
    artist: "Alice Cooper",
    rank: 487,
    title: "I'm Eighteen",
    year: 1971,
  },
  {
    album: "Kiss Me, Kiss Me, Kiss Me",
    artist: "The Cure",
    rank: 488,
    title: "Just Like Heaven",
    year: 1987,
  },
  {
    album: "The Very Best of the Drifters",
    artist: "The Drifters",
    rank: 489,
    title: "Under the Boardwalk",
    year: 1964,
  },
  {
    album: "A Rush of Blood to the Head",
    artist: "Coldplay",
    rank: 490,
    title: "Clocks",
    year: 2002,
  },
  {
    album: "I Love Rock 'N Roll",
    artist: "Joan Jett and The Blackhearts",
    rank: 491,
    title: "I Love Rock 'N Roll",
    year: 1981,
  },
  {
    album: "I Will Survive: The Anthology",
    artist: "Gloria Gaynor",
    rank: 492,
    title: "I Will Survive",
    year: 1978,
  },
  {
    album: "Oracular Spectacular",
    artist: "MGMT",
    rank: 493,
    title: "Time to Pretend",
    year: 2008,
  },
  {
    album: "Chocolate Factory",
    artist: "R. Kelly",
    rank: 494,
    title: "Ignition (Remix)",
    year: 2003,
  },
  {
    album: "Sticky Fingers",
    artist: "The Rolling Stones",
    rank: 495,
    title: "Brown Sugar",
    year: 1971,
  },
  {
    album: "Running on Empty",
    artist: "Jackson Browne",
    rank: 496,
    title: "Running On Empty",
    year: 1977,
  },
  {
    album: "The Rising",
    artist: "Bruce Springsteen",
    rank: 497,
    title: "The Rising",
    year: 2002,
  },
  {
    album: "Some Girls",
    artist: "The Rolling Stones",
    rank: 498,
    title: "Miss You",
    year: 1978,
  },
  {
    album: "Weezer",
    artist: "Weezer",
    rank: 499,
    title: "Buddy Holly",
    year: 1994,
  },
  {
    album: "The Ultimate Collection",
    artist: "Smokey Robinson and the Miracles",
    rank: 500,
    title: "Shop Around",
    year: 1960,
  },
];
